replicaCount: 1

image:
  repository: john3210of/nine-docs-repo
  tag: c53b245
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  SECRET_KEY: "test-key"
  DEBUG: True