replicaCount: 1

image:
  repository: john3210of/nine-docs-repo
  tag: 34db4da
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  SECRET_KEY: ""
  DEBUG: ""