apiVersion: v1
kind: Service
metadata:
  name: article
  labels:
    app: article
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: article
